language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zor/react-test npm test -- --coverage

after_success:
  - docker build -t zor/multi-client ./client
  - docker build -t zor/multi-nginx ./nginx
  - docker build -t zor/multi-server ./server
  - docker build -t zor/multi-worker ./worker

  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to the docker hub
  - docker push -t zor/multi-client 
  - docker push -t zor/multi-nginx 
  - docker push -t zor/multi-server 
  - docker push -t zor/multi-worker 
